### PR TITLE
fix: tweaking theme provider

### PR DESCRIPTION
**Pull request by kohinoor98**
solves #48

### CODE REVIEW

**Review by satnaing — APPROVED** [review]

**Comment by satnaing** [comment]
Thanks for pointing out this issue and PR.

I also made a couple of changes

- disable eslint warning
- update `setThemeState` to `_setTheme`

**Comment by kohinoor98** [comment]
Thanks for such a beautiful template! If there are any additional issues I could work on, plz let me know, would love to contribute

**Comment by satnaing** [comment]
Thanks @kohinoor98 
You can try the ESLint upgrading issue #24 
However, when I opened that issue, there was no stable React19-compatible ESLint version.
I'm not sure if it's out now or not tho.
You can try that if you want (or if you're interested in doing that)

**Comment by kohinoor98** [comment]
For sure, let me check it over the weekend!

**Pull request merged**
